# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('question_type', models.CharField(choices=[('singlelinetext', 'Single Line Text'), ('paragraphtext', 'Paragraph Text')], max_length=30)),
                ('required', models.BooleanField()),
            ],
        ),
    ]
